### ISSUE TITLE
week 04 - day 01 - octocats - intro to react

### ISSUE THREAD

**Issue by sgacio** [sgacio/assignments#12]
# React-ify Octocats

Octodex is a fun way to celebrate a powerful tool we use for development. In that same spirit, recreate [this site](https://octodex.github.com/)

You'll identify the main `Component`s on the page and create React components for each, breaking down those `Component`s into smaller ones as needed.

## Objectives

- Learn to identify parts of a web site as `Component`s
- Use `app-app` (GAMMA stack) to build a React project
- Understand and use React components

## Stretch Objectives

- Understand and use "props" in React
- Use `Array.prototype.map` to render a collection of components in React

### Explorer Mode

- [x] Figure out the main components of the page. These will be the main components in your `<App>` component.
- [x] Create your React app
- [x] Your CSS should be in `index.css`
- [x] You should have at _least_ two components...
- [x] Clear out the implementation in the `render` method of `App` and have it render your main components.
- [x] Use props to try to reuse components

### Adventure Mode

- [ ] Place the definition of each Octocat in an `array` of objects and use `map` to generate the Octocat components

### Epic Mode

- [ ] Put the `array` of Octocats in a `octocats.json` file and `import` that into your app.
- _OR_
- [ ] Use the `fetch` api to retrieve the list of Octocats from [this api](https://sdg-octodex.herokuapp.com/) instead

## Additional Resources

- [React Documentation](https://reactjs.org/docs/getting-started.html)
- [.map, .reduce & .filter, Oh My!](https://www.datchley.name/working-with-collections/)
- [Array.prototype.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

**Comment by sgacio** [comment]
https://github.com/sgacio/react-ify

**Comment by mdewey** [comment]
Watch your naming conventions, but good job
